name: Bump NPM version

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release type (one of): patch, minor, major, prepatch, preminor, premajor, prerelease'
        required: true

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Git configuration
        run: |
          git config user.name "Leukeleu Deployer"
          git config user.email "deployer@leukeleu.nl"

      - name: Bump version
        run: npm version ${{ github.event.inputs.release-type }}

      - name: Push changes to repository
        run: git push https://${{ secrets.DEPLOYER_RELEASE_TOKEN }}:x-oauth-basic@github.com/leukeleu/prettier-config.git && git push https://${{ secrets.DEPLOYER_RELEASE_TOKEN }}:x-oauth-basic@github.com/leukeleu/prettier-config.git --tags
